import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../providers/matches_providers.dart';
import '../../../groups/data/models/group_model.dart';
import '../../../groups/presentation/providers/groups_providers.dart';
import '../../../groups/presentation/views/group_detail_screen.dart';

class MatchTeamsScreen extends ConsumerWidget {
  const MatchTeamsScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final teamsAsync = ref.watch(matchTeamsProvider);

    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => context.pop(),
        ),
        title: const Text('Equipos de partidos'),
        actions: [
          IconButton(
            icon: const Icon(Icons.auto_awesome),
            tooltip: 'Auto-generar equipos equilibrados',
            onPressed: () => _showAutoGenerateDialog(context, ref),
          ),
          IconButton(
            icon: const Icon(Icons.refresh),
            tooltip: 'Actualizar',
            onPressed: () => ref.invalidate(matchTeamsProvider),
          ),
        ],
      ),
      body: teamsAsync.when(
        data: (teams) {
          if (teams.isEmpty) {
            return ListView(
              children: const [
                SizedBox(height: 100),
                Padding(
                  padding: EdgeInsets.all(24),
                  child: Text(
                    'Aún no hay equipos de partidos.\nCréalos aquí; son independientes de los grupos de competición y no cuentan en la clasificación.',
                    textAlign: TextAlign.center,
                    style: TextStyle(fontSize: 15, color: Colors.grey),
                  ),
                ),
              ],
            );
          }
          return ListView.builder(
            itemCount: teams.length,
            itemBuilder: (context, index) {
              final t = teams[index];
              return Card(
                margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
                child: ListTile(
                  leading: const CircleAvatar(child: Icon(Icons.shield_outlined)),
                  title: Text(t.nombre, style: const TextStyle(fontWeight: FontWeight.bold)),
                  subtitle: const Text('Toca para ver y editar la plantilla'),
                  onTap: () {
                    Navigator.of(context).push(
                      MaterialPageRoute(
                        builder: (_) => GroupDetailScreen(
                          group: GroupModel(
                            id: t.id,
                            nombre: t.nombre,
                            createdAt: DateTime.now(),
                          ),
                        ),
                      ),
                    ).then((_) => ref.invalidate(matchTeamsProvider));
                  },
                  trailing: IconButton(
                    icon: const Icon(Icons.delete, color: Colors.grey),
                    onPressed: () async {
                      final ok = await showDialog<bool>(
                        context: context,
                        builder: (c) => AlertDialog(
                          title: const Text('Eliminar equipo'),
                          content: Text('¿Borrar el equipo "${t.nombre}"?'),
                          actions: [
                            TextButton(onPressed: () => Navigator.pop(c, false), child: const Text('Cancelar')),
                            TextButton(onPressed: () => Navigator.pop(c, true), child: const Text('Eliminar', style: TextStyle(color: Colors.red))),
                          ],
                        ),
                      );
                      if (ok == true) {
                        try {
                          await ref.read(matchesRepositoryProvider).deleteTeam(t.id);
                          ref.invalidate(matchTeamsProvider);
                        } catch (e) {
                          if (context.mounted) {
                            ScaffoldMessenger.of(context).showSnackBar(
                              SnackBar(content: Text('Error: $e')),
                            );
                          }
                        }
                      }
                    },
                  ),
                ),
              );
            },
          );
        },
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (e, s) => Center(child: Text('Error: $e')),
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () => _showCreateDialog(context, ref),
        icon: const Icon(Icons.add),
        label: const Text('Nuevo equipo'),
      ),
    );
  }

  void _showAutoGenerateDialog(BuildContext context, WidgetRef ref) {
    final numController = TextEditingController();
    final prefixController = TextEditingController(text: 'Equipo');

    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Auto-generar equipos de partido'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text(
              'Creará equipos equilibrados repartiendo a los jugadores según su nivel, edad y posición (snake draft). No cuentan en la clasificación de competición ni alteran los grupos de competición.',
              style: TextStyle(fontSize: 13),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: prefixController,
              decoration: const InputDecoration(labelText: 'Prefijo (ej: Equipo)'),
            ),
            TextField(
              controller: numController,
              decoration: const InputDecoration(labelText: 'Número de equipos'),
              keyboardType: TextInputType.number,
            ),
          ],
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('Cancelar')),
          ElevatedButton(
            onPressed: () async {
              final numTeams = int.tryParse(numController.text.trim()) ?? 0;
              final prefix = prefixController.text.trim();
              if (numTeams <= 0 || prefix.isEmpty) return;
              try {
                showDialog(
                  context: context,
                  barrierDismissible: false,
                  builder: (c) => const Center(child: CircularProgressIndicator()),
                );
                await ref.read(groupsRepositoryProvider).autoGenerateBalancedTeams(
                      numTeams,
                      prefix,
                      isMatchTeam: true,
                    );
                ref.invalidate(matchTeamsProvider);
                if (context.mounted) {
                  Navigator.pop(context); // loading
                  Navigator.pop(ctx); // dialog
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text('Equipos de partido generados')),
                  );
                }
              } catch (e) {
                if (context.mounted) {
                  Navigator.pop(context); // loading
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
                  );
                }
              }
            },
            child: const Text('Generar'),
          ),
        ],
      ),
    );
  }

  void _showCreateDialog(BuildContext context, WidgetRef ref) {
    final controller = TextEditingController();
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Nuevo equipo de partido'),
        content: TextField(
          controller: controller,
          autofocus: true,
          decoration: const InputDecoration(labelText: 'Nombre del equipo'),
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('Cancelar')),
          ElevatedButton(
            onPressed: () async {
              final nombre = controller.text.trim();
              if (nombre.isEmpty) return;
              try {
                await ref.read(matchesRepositoryProvider).createTeam(nombre);
                ref.invalidate(matchTeamsProvider);
                if (ctx.mounted) Navigator.pop(ctx);
              } catch (e) {
                if (ctx.mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(content: Text('Error: $e')),
                  );
                }
              }
            },
            child: const Text('Crear'),
          ),
        ],
      ),
    );
  }
}
