import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../providers/groups_providers.dart';
import '../../../matches/presentation/providers/matches_providers.dart';
import 'group_detail_screen.dart';

class GroupManagementScreen extends ConsumerWidget {
  const GroupManagementScreen({super.key});

  void _showCreateGroupDialog(BuildContext context, WidgetRef ref) {
    final nameController = TextEditingController();
    final catController = TextEditingController();
    bool esPartido = false;

    showDialog(
      context: context,
      builder: (context) => StatefulBuilder(
        builder: (context, setState) => AlertDialog(
          title: const Text('Nuevo Grupo'),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TextField(
                controller: nameController,
                decoration: const InputDecoration(labelText: 'Nombre *'),
              ),
              TextField(
                controller: catController,
                decoration: const InputDecoration(
                    labelText: 'Categoría (Opcional, ej: Alevín)'),
              ),
              const SizedBox(height: 8),
              SwitchListTile(
                contentPadding: EdgeInsets.zero,
                value: esPartido,
                onChanged: (v) => setState(() => esPartido = v),
                title: const Text('Equipo de partido'),
                subtitle: const Text(
                  'No cuenta en la clasificación de competición',
                  style: TextStyle(fontSize: 12),
                ),
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Cancelar'),
            ),
            ElevatedButton(
              onPressed: () async {
                if (nameController.text.trim().isEmpty) return;
                try {
                  await ref.read(groupsRepositoryProvider).createGroup(
                        nameController.text.trim(),
                        catController.text.trim().isEmpty
                            ? null
                            : catController.text.trim(),
                        isMatchTeam: esPartido,
                      );
                  ref.invalidate(groupsProvider);
                  if (esPartido) ref.invalidate(matchTeamsProvider);
                  if (context.mounted) {
                    Navigator.pop(context);
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: Text(esPartido
                            ? 'Equipo de partido creado'
                            : 'Grupo creado correctamente'),
                      ),
                    );
                  }
                } catch (e) {
                  if (context.mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
                    );
                  }
                }
              },
              child: const Text('Crear'),
            ),
          ],
        ),
      ),
    );
  }

  void _showAutoGenerateDialog(BuildContext context, WidgetRef ref) {
    final numController = TextEditingController();
    final prefixController = TextEditingController(text: 'Equipo');

    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Auto-generar Equipos'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text(
              'Esto creará nuevos equipos de competición y distribuirá automáticamente a todos los jugadores de forma equilibrada según su edad (snake draft).',
              style: TextStyle(fontSize: 13),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: prefixController,
              decoration: const InputDecoration(labelText: 'Prefijo (ej: Equipo)'),
            ),
            TextField(
              controller: numController,
              decoration: const InputDecoration(labelText: 'Número de equipos'),
              keyboardType: TextInputType.number,
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancelar'),
          ),
          ElevatedButton(
            onPressed: () async {
              final numTeams = int.tryParse(numController.text.trim()) ?? 0;
              final prefix = prefixController.text.trim();
              if (numTeams <= 0 || prefix.isEmpty) return;

              try {
                // Muestra loading
                showDialog(
                  context: context,
                  barrierDismissible: false,
                  builder: (c) => const Center(child: CircularProgressIndicator()),
                );

                await ref.read(groupsRepositoryProvider)
                    .autoGenerateBalancedTeams(numTeams, prefix);
                ref.invalidate(groupsProvider);

                if (context.mounted) {
                  Navigator.pop(context); // close loading
                  Navigator.pop(context); // close dialog
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text('Equipos generados correctamente')),
                  );
                }
              } catch (e) {
                if (context.mounted) {
                  Navigator.pop(context); // close loading
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
                  );
                }
              }
            },
            child: const Text('Generar'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final groupsAsync = ref.watch(groupsProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Grupos de Competición'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => context.pop(),
        ),
        actions: [
          IconButton(
            tooltip: 'Actualizar',
            icon: const Icon(Icons.refresh),
            onPressed: () => ref.invalidate(groupsProvider),
          ),
          IconButton(
            tooltip: 'Auto-generar equipos equilibrados',
            icon: const Icon(Icons.auto_awesome),
            onPressed: () => _showAutoGenerateDialog(context, ref),
          ),
        ],
      ),
      body: groupsAsync.when(
        data: (groups) {
          return RefreshIndicator(
            onRefresh: () async {
              ref.invalidate(groupsProvider);
              await ref.read(groupsProvider.future);
            },
            child: groups.isEmpty
                ? ListView(
                    children: const [
                      SizedBox(height: 120),
                      Center(child: Text('No hay grupos creados aún.')),
                    ],
                  )
                : ListView.builder(
            itemCount: groups.length,
            itemBuilder: (context, index) {
              final group = groups[index];
              return Card(
                margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                child: ListTile(
                  leading: const CircleAvatar(
                    child: Icon(Icons.group),
                  ),
                  title: Text(group.nombre,
                      style: const TextStyle(fontWeight: FontWeight.bold)),
                  subtitle: Text(group.categoria ?? 'Sin categoría'),
                  trailing: const Icon(Icons.arrow_forward_ios, size: 16),
                  onTap: () {
                    Navigator.of(context).push(
                      MaterialPageRoute(
                        builder: (_) => GroupDetailScreen(group: group),
                      ),
                    );
                  },
                ),
              );
            },
          ),
          );
        },
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (e, s) => Center(child: Text('Error: $e')),
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () => _showCreateGroupDialog(context, ref),
        icon: const Icon(Icons.add),
        label: const Text('Añadir Grupo'),
      ),
    );
  }
}
